#!/bin/sh
PHP_INI_SCAN_DIR='/var/www/u2797116/data/php-bin-regru-php82/englishlearn62.ru:'
PHPRC='/var/www/u2797116/data/php-bin-regru-php82'
export PHP_INI_SCAN_DIR
export PHPRC
exec /opt/php/8.2/bin/php-cgi
